version: '3.9'

services:
  db:
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres_volume
